version: '3.0'
services:
  web:
    image: odoo:13.0
    depends_on:
      - db
    ports:
      - "8066:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    networks: 
      - odoonet
  
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks: 
      - odoonet
  
  pgadmin4:
    image: dpage/pgadmin4:4.25
    environment: 
        PGADMIN_DEFAULT_EMAIL: shahjalal.tipu@gmail.com
        PGADMIN_DEFAULT_PASSWORD: admin1234
        PGADMIN_LISTEN_PORT: 80
    ports:
        - "8888:80"
    volumes:
        - pgadmin4:/var/lib/pgadmin
    networks: 
        - odoonet

volumes:
  odoo-web-data:
  odoo-db-data:
  pgadmin4:

networks: 
  odoonet: 
    driver: bridge
